export const CATEGORIES = {
  social: 'Social profiles',
  knowledge: 'Knowledge graph and company data',
  reviews: 'Review and software directories',
  dev: 'Developer and package listings',
  stores: 'App and extension stores',
  agents: 'AI agent and automation directories',
  other: 'Other profiles',
};

export const PLATFORMS = [
  {
    id: 'x',
    name: 'X (Twitter)',
    category: 'social',
    match: ['x.com', 'twitter.com'],
    claimUrl: 'https://x.com/i/flow/signup',
    effort: 'easy',
    guide: ['Create the account with the brand handle.', 'Set name, logo as avatar, banner, short description as bio.', 'Add the homepage URL to the profile.'],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn company page',
    category: 'social',
    match: ['linkedin.com/company'],
    claimUrl: 'https://www.linkedin.com/company/setup/new/',
    effort: 'easy',
    guide: ['Create a company page from a personal LinkedIn account.', 'Paste name, logo, short description as tagline, long description as About.', 'Set the website URL and industry.'],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'social',
    match: ['instagram.com'],
    claimUrl: 'https://www.instagram.com/accounts/emailsignup/',
    effort: 'easy',
    guide: ['Create the account with the brand handle, switch to a business account.', 'Set logo as avatar, short description as bio, homepage as the link.'],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'social',
    match: ['tiktok.com'],
    claimUrl: 'https://www.tiktok.com/signup',
    effort: 'easy',
    guide: ['Create the account with the brand handle.', 'Set logo, bio from the short description, and the homepage link (business accounts get a clickable link).'],
  },
  {
    id: 'youtube',
    name: 'YouTube channel',
    category: 'social',
    match: ['youtube.com'],
    claimUrl: 'https://www.youtube.com/create_channel',
    effort: 'easy',
    guide: ['Create a brand channel with the @handle.', 'Set logo, banner, short description, and the homepage in channel links.'],
  },
  {
    id: 'facebook',
    name: 'Facebook page',
    category: 'social',
    match: ['facebook.com'],
    claimUrl: 'https://www.facebook.com/pages/create',
    effort: 'easy',
    guide: ['Create a business page.', 'Set logo, banner, category, short description as the intro, homepage as website.'],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    category: 'social',
    match: ['pinterest.com'],
    claimUrl: 'https://www.pinterest.com/business/create/',
    effort: 'easy',
    guide: ['Create a business account with the brand handle.', 'Set logo, short description as About, and claim the website domain in settings.'],
  },
  {
    id: 'threads',
    name: 'Threads',
    category: 'social',
    match: ['threads.com', 'threads.net'],
    claimUrl: 'https://www.threads.com/',
    effort: 'easy',
    guide: ['Log in with the brand Instagram account; the profile carries over.', 'Confirm bio and link match the kit.'],
  },
  {
    id: 'bluesky',
    name: 'Bluesky',
    category: 'social',
    match: ['bsky.app'],
    claimUrl: 'https://bsky.app/',
    effort: 'easy',
    guide: ['Create the account.', 'Set the handle to the brand domain: Settings, Change handle, "I have my own domain", add the shown _atproto TXT record.', 'Set logo, banner, short description as bio.'],
  },
  {
    id: 'mastodon',
    name: 'Mastodon',
    category: 'social',
    match: ['mastodon.social', 'mastodon.', 'fosstodon.org', 'mstdn.'],
    claimUrl: 'https://mastodon.social/auth/sign_up',
    effort: 'easy',
    guide: ['Create the account with the brand handle.', 'Set logo, banner, short description as bio, and the homepage as a profile field.', 'Add <link rel="me" href="https://mastodon.social/@handle"> to the site head, then re-save the profile field so it shows as verified.', 'Profile links are nofollow; the value is the verified rel=me identity loop, not link equity.'],
  },
  {
    id: 'github',
    name: 'GitHub organization',
    category: 'dev',
    match: ['github.com'],
    claimUrl: 'https://github.com/organizations/plan',
    effort: 'easy',
    guide: ['Create the organization with the brand name.', 'Set logo, short description, homepage URL, and pin real repositories.'],
  },
  {
    id: 'npm',
    name: 'npm package',
    category: 'dev',
    match: ['npmjs.com'],
    claimUrl: 'https://www.npmjs.com/',
    effort: 'easy',
    guide: ['Publish a package under the brand name, even a small SDK or CLI counts.', 'Point the package.json homepage field at the site so the listing links back.'],
  },
  {
    id: 'stackshare',
    name: 'StackShare',
    category: 'dev',
    match: ['stackshare.io'],
    claimUrl: 'https://stackshare.io/create-stack',
    effort: 'easy',
    guide: ['Create an account and add the product as a tool.', 'Set logo, short description, homepage.'],
  },
  {
    id: 'chrome-web-store',
    name: 'Chrome Web Store',
    category: 'stores',
    match: ['chromewebstore.google.com'],
    claimUrl: 'https://chrome.google.com/webstore/devconsole',
    effort: 'medium',
    guide: ['Publish the extension from the developer console (one-time $5 registration).', 'Use the kit logo, short description, and homepage in the listing.'],
  },
  {
    id: 'edge-addons',
    name: 'Microsoft Edge Add-ons',
    category: 'stores',
    match: ['microsoftedge.microsoft.com'],
    claimUrl: 'https://partner.microsoft.com/dashboard/microsoftedge',
    effort: 'medium',
    guide: ['Publish through Partner Center (free).', 'Reuse the Chrome listing assets and text.'],
  },
  {
    id: 'firefox-addons',
    name: 'Firefox Add-ons',
    category: 'stores',
    match: ['addons.mozilla.org'],
    claimUrl: 'https://addons.mozilla.org/developers/',
    effort: 'medium',
    guide: ['Publish through the Add-on Developer Hub (free).', 'Reuse the Chrome listing assets and text; Mozilla runs a human review.'],
  },
  {
    id: 'opera-addons',
    name: 'Opera add-ons',
    category: 'stores',
    match: ['addons.opera.com'],
    claimUrl: 'https://addons.opera.com/developer/',
    effort: 'medium',
    guide: ['Publish through the Opera developer portal (free); Chromium extensions upload as-is.', 'Reuse the Chrome listing assets and text.'],
  },
  {
    id: 'wikidata',
    name: 'Wikidata',
    category: 'knowledge',
    match: ['wikidata.org'],
    claimUrl: 'https://www.wikidata.org/wiki/Special:NewItem',
    effort: 'easy',
    guide: ['Register, then create a new item. Notability needs at least one serious external reference.', 'Add statements: instance of, official website, inception, founded by.', 'Add external IDs (Crunchbase, X, GitHub) so the item cross-links.', 'Description is a lowercase neutral phrase, not marketing.'],
  },
  {
    id: 'crunchbase',
    name: 'Crunchbase',
    category: 'knowledge',
    match: ['crunchbase.com'],
    claimUrl: 'https://www.crunchbase.com/add-new',
    effort: 'easy',
    guide: ['Create the organization profile.', 'Paste name, logo, short description, founded date, homepage, and founder.'],
  },
  {
    id: 'f6s',
    name: 'F6S',
    category: 'knowledge',
    match: ['f6s.com'],
    claimUrl: 'https://www.f6s.com/company-signup',
    effort: 'easy',
    guide: ['Create the company profile.', 'Paste name, logo, short description, homepage.'],
  },
  {
    id: 'e27',
    name: 'e27',
    category: 'knowledge',
    match: ['e27.co'],
    claimUrl: 'https://e27.co/startups/',
    effort: 'easy',
    guide: ['Register and add the startup profile.', 'Paste name, logo, short description, homepage.'],
  },
  {
    id: 'product-hunt',
    name: 'Product Hunt',
    category: 'reviews',
    match: ['producthunt.com'],
    claimUrl: 'https://www.producthunt.com/products/new',
    effort: 'easy',
    guide: ['Add the product page (a launch is separate and optional).', 'Set logo, banner as gallery image, short description as tagline, long description as the description.'],
  },
  {
    id: 'saashub',
    name: 'SaaSHub',
    category: 'reviews',
    match: ['saashub.com'],
    claimUrl: 'https://www.saashub.com/submit',
    effort: 'easy',
    guide: ['Submit the product.', 'Paste name, logo, short description, homepage; add alternatives so it lands in the right comparisons.'],
  },
  {
    id: 'sourceforge',
    name: 'SourceForge',
    category: 'reviews',
    match: ['sourceforge.net'],
    claimUrl: 'https://sourceforge.net/software/vendors/',
    effort: 'easy',
    guide: ['Add the product through the business software directory.', 'Paste name, logo, long description; expect a sales follow-up, the free listing is enough.'],
  },
  {
    id: 'g2',
    name: 'G2',
    category: 'reviews',
    match: ['g2.com'],
    claimUrl: 'https://sell.g2.com/',
    effort: 'easy',
    guide: ['Search G2 first; a seeded profile may already exist.', 'Claim or create it, then set logo, short description, homepage, category.'],
  },
  {
    id: 'capterra',
    name: 'Capterra',
    category: 'reviews',
    match: ['capterra.com'],
    claimUrl: 'https://www.capterra.com/vendors/',
    effort: 'easy',
    guide: ['Apply once as a vendor; the listing covers Capterra, GetApp, and Software Advice (shared Gartner backend).', 'Pick the category competitors rank in; review takes weeks.'],
  },
  {
    id: 'getapp',
    name: 'GetApp',
    category: 'reviews',
    match: ['getapp.com'],
    claimUrl: 'https://www.capterra.com/vendors/',
    effort: 'easy',
    guide: ['Comes with the Capterra vendor listing; no separate submission.'],
    optional: true,
  },
  {
    id: 'software-advice',
    name: 'Software Advice',
    category: 'reviews',
    match: ['softwareadvice.com'],
    claimUrl: 'https://www.capterra.com/vendors/',
    effort: 'easy',
    guide: ['Comes with the Capterra vendor listing; no separate submission.'],
    optional: true,
  },
  {
    id: 'trustpilot',
    name: 'Trustpilot',
    category: 'reviews',
    match: ['trustpilot.com'],
    claimUrl: 'https://business.trustpilot.com/',
    effort: 'easy',
    guide: ['The review page exists per domain already; claim it from the business portal.', 'Set logo and short description on the claimed profile.'],
  },
  {
    id: 'alternativeto',
    name: 'AlternativeTo',
    category: 'reviews',
    match: ['alternativeto.net'],
    claimUrl: 'https://alternativeto.net/',
    effort: 'easy',
    guide: ['Register, then add the app via Manage.', 'Submit neutral wording; moderators edit promotional text.', 'List the real alternatives so the entity sits next to its category.'],
  },
];

PLATFORMS.push(
  {
    id: 'claude-plugin-directory',
    name: 'Claude plugin directory',
    category: 'agents',
    match: ['claude.com/plugins', 'claude-plugins-community'],
    claimUrl: 'https://platform.claude.com/plugins/submit',
    effort: 'hard',
    guide: [
      'Build a Claude Code plugin: a public repo with .claude-plugin/plugin.json and a skill or MCP server wired to your product API.',
      'Run `claude plugin validate .`, then submit the repo through the Console form.',
      'Approval lands the plugin in the anthropics/claude-plugins-community catalog; users install it with /plugin install <name>@claude-community.',
    ],
  },
  {
    id: 'chatgpt-apps',
    name: 'ChatGPT app directory',
    category: 'agents',
    match: ['chatgpt.com/apps'],
    claimUrl: 'https://platform.openai.com/plugins',
    effort: 'hard',
    guide: [
      'Build and host an MCP server for your product (OpenAI Apps SDK).',
      'Submit through the OpenAI developer platform: directory metadata, privacy and terms URLs, starter prompts, and a read-only/open-world/destructive justification per tool.',
      'Approved apps appear in the in-ChatGPT app directory and load via @mention.',
    ],
  },
  {
    id: 'zapier',
    name: 'Zapier app directory',
    category: 'agents',
    match: ['zapier.com'],
    claimUrl: 'https://developer.zapier.com/',
    effort: 'hard',
    guide: [
      'Build the integration on the Zapier developer platform against your public API.',
      "Meet Zapier's publishing requirements and submit for review to go from private beta to public.",
      'The public listing at zapier.com/apps/<name> goes into sameAs once live.',
    ],
  },
  {
    id: 'mcp-registry',
    name: 'Official MCP registry',
    category: 'agents',
    match: ['registry.modelcontextprotocol.io'],
    claimUrl: 'https://registry.modelcontextprotocol.io',
    effort: 'medium',
    guide: [
      'Write a server.json with the com.<domain>/<server> name and the remote streamable-http URL.',
      'Prove domain ownership: apex TXT record, then `mcp-publisher login dns`.',
      '`mcp-publisher publish`; aggregator directories scrape this registry, so downstream listings follow.',
    ],
  },
  {
    id: 'smithery',
    name: 'Smithery',
    category: 'agents',
    match: ['smithery.ai'],
    claimUrl: 'https://smithery.ai/new',
    effort: 'medium',
    guide: ['Add the server at smithery.ai/new with the remote URL and auth details.', 'The server page goes into sameAs once live.'],
  },
  {
    id: 'pulsemcp',
    name: 'PulseMCP',
    category: 'agents',
    match: ['pulsemcp.com'],
    claimUrl: 'https://www.pulsemcp.com',
    effort: 'medium',
    guide: ['PulseMCP indexes the official MCP registry; check for your server page after publishing there.', 'Submit manually through the site if it has not appeared.'],
  },
  {
    id: 'mcp-so',
    name: 'mcp.so',
    category: 'agents',
    match: ['mcp.so'],
    claimUrl: 'https://mcp.so/submit',
    effort: 'medium',
    guide: ['Submit the server with the remote URL, name, and short description.', 'The server page goes into sameAs once live.'],
  },
  {
    id: 'glama-mcp',
    name: 'Glama MCP directory',
    category: 'agents',
    match: ['glama.ai'],
    claimUrl: 'https://glama.ai/mcp/servers',
    effort: 'medium',
    guide: ['Claim or add the server in the Glama MCP directory.', 'The server page goes into sameAs once live.'],
  },
  {
    id: 'awesome-mcp-servers',
    name: 'awesome-mcp-servers',
    category: 'agents',
    match: ['github.com/punkpeye/awesome-mcp-servers'],
    claimUrl: 'https://github.com/punkpeye/awesome-mcp-servers',
    effort: 'easy',
    guide: ['Fork the list and add the server under the right category with a one-line description.', 'Open the PR; the merged line is the listing.'],
  },
  {
    id: 'n8n',
    name: 'n8n integrations',
    category: 'agents',
    match: ['n8n.io'],
    claimUrl: 'https://docs.n8n.io/integrations/creating-nodes/',
    effort: 'hard',
    guide: [
      'Build a community node (an npm package with the n8n-nodes- prefix) against your API.',
      'Publish it to npm, then submit it for n8n verification so it appears in the integrations catalog.',
      'The listing at n8n.io/integrations/<name> goes into sameAs once live.',
    ],
  }
);

export const PAID_HOSTS = ['theresanaiforthat.com', 'betalist.com', 'uneed.best', 'toolify.ai', 'futurepedia.io'];

export const isPaidHost = (url) => PAID_HOSTS.some((host) => url.toLowerCase().includes(host));

export const matchPlatform = (url) => {
  const normalized = url.toLowerCase();
  let best = null;
  let bestLength = 0;

  for (const platform of PLATFORMS) {
    for (const fragment of platform.match) {
      if (normalized.includes(fragment) && fragment.length > bestLength) {
        best = platform;
        bestLength = fragment.length;
      }
    }
  }

  return best;
};
